-- =============================================================================
-- SUPERSEDED — do not run this file on new environments.
-- =============================================================================
-- Replaced by: supabase/review_model_final.sql
--
-- Why:
-- Sprint 4 added optional columns (stay_duration, cost_to_work, wifi_reliability,
-- busyness, coffee_quality, food_quality) plus get_cafe_cost_to_work_summary.
-- The current Log Workspace flow does NOT write those fields. Live production
-- never received this migration; aligning the app to the live schema removed
-- those UI fields rather than inventing unused columns.
--
-- Kept for history only. Use review_model_final.sql instead.
-- =============================================================================

-- (Intentionally empty of executable DDL. See review_model_final.sql.)
